### ISSUE TITLE
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super.

### ISSUE THREAD

**Issue by colstrom** [niho/related#20]
`related` currently triggers a few deprecation warnings, regarding the use of `alias_method_chain`. The three uses are here:
- https://github.com/sutajio/related/blob/v0.6.5/lib/related/node.rb#L174
- https://github.com/sutajio/related/blob/v0.6.5/lib/related/node.rb#L191
- https://github.com/sutajio/related/blob/v0.6.5/lib/related/node.rb#L208

I'm not entirely clear what the _intent_ is behind those three lines. If you could shed some light on the intent, I'd be happy to send patches amending the code.

**Comment by niho** [comment]
The Redis client is unable to perform set operations (sdiff, sunion, sinter) on pairs of keys that are stored in separate Redis instances when running a distributed setup. To handle this edge case Related instead fetches both keys and performs the set operations locally, which is somewhat slower, but will always work. This is explicitly only done when the Redis client raises a `Redis::Distributed::CannotDistribute` exception in order to not degrade the performance of the general case.

The point of using `alias_method_chain` and separating the implementation in pairs of methods (e.g. `union` and `union_with_distributed_fallback`) is simply to keep the code as clean and maintainable as possible, clearly separating out distinct concerns. It also allows you to call the automatically generated method `union_without_distributed_fallback` which can be useful in certain cases.

I guess this can be changed to use the `prepend` method instead of `alias_method_chain`, which seems to be the preferred way of doing these kind of things in Ruby 2.0. So moving the *_with_distributed_fallback methods to a separate module (`Related::Node::DistributedFallback` might be a good name) and then adding a `prepend DistributedFallback` to `Related::Node::Query` would probably do the trick.

**Caveat:** I'm not really familiar with the new `prepend` method, as I haven't had the opportunity to actually use it. Thus my suggestion on how to use it might be uninformed and/or stupid. Take it with a grain of salt. That said, it seems like the way forward.
